### ISSUE TITLE
Add .toString method to Matrix instances

### ISSUE THREAD

**Issue by slichte** [mljs/matrix#101]
Hi!
At first i'd like to say that this is a really cool and handy library, Very complete, very intuitive in usage. Nice idea with this chaining vs. statics pattern.

We all know, however, that despite modern browsers' and IDEs' great debugging capabilites, good ol' console.log is still a weapon of choice in JavaScript development. So if you have some time left for the next release:
could you add a .toString() method to your Matrix class for nicely formatted output? This would be really great!

Thanks a lot and take care.

**Comment by targos** [comment]
Hi, thanks for the kind words!
Are you asking this for the browser version of the library?
In Node.js, we already have a custom formatter that runs when console.log is called. I can look into exposing it somehow in a toString method.

**Comment by slichte** [comment]
Hi!
Yes, I'm using the library in a TypeScript project.
Didn't know about the custom formatter, this would be great I guess. Thanks a lot!

**Comment by targos** [comment]
Okay, I'm just wondering what's causing problems when you `console.log(someMatrix)` that a toString method would solve?

**Comment by slichte** [comment]
Hi! Thanks for your reply. A .toString() method could provide some quick overview of the whole matrix. Of course you're right, you can get all the data with just a console.log(mat), but it's difficult to check the contents of i.e. a 4x4 matrix. An output like that would be great:
[ 11 12 13 14
  21 22 23 24
  31 32 33 34
  41 42 43 44 ]

So I could see at first glance if my columns and rows are what I expect them to be.
Have a nice day!

**Comment by targos** [comment]
I released v6.5.0 with a toString method: https://mljs.github.io/matrix/classes/abstractmatrix.html#tostring

**Comment by slichte** [comment]
Hi!
Just used the new feature. Very nice. Thanks so much!
Have a nice day!

![screen_matrix_toString](https://user-images.githubusercontent.com/16239166/81300676-3cdfda00-9078-11ea-9c0b-7664abf7ee8c.png)
