### ISSUE TITLE
Add one vector to matrix

### ISSUE THREAD

**Issue by Toso82** [mljs/matrix#104]
@targos  Maybe it is stupid question i don't find there is a function to add ones vector at start position of Matrix object.

**Comment by targos** [comment]
Do you mean to add a new row or column (increasing the size of the matrix)?

**Comment by Toso82** [comment]
Yes i mean i have to matrix like this

[2,4]
[3,6]

and i want to change like this

[1,2,4]
[1,3,6]

**Comment by targos** [comment]
This should be possible with the `addRow` and `addColumn` methods.
I realize they are not properly documented, sorry about that!

Example:

```js
const matrix = new Matrix([[2,4],[3,6]])
matrix.addColumn(0, [1, 1]) // 0 is the index for the new column
```

**Comment by Toso82** [comment]
@targos No problem i find and use this .addColumn() as you suggest but there is error

```TS
ERROR in src/app/shared/RegressioneLineare.ts:60:11 - error TS2339: Property 'addColumn' does not exist on type 'Matrix'
 ```

**Comment by targos** [comment]
Yes, that's related to what I said about documentation.
Would you like to open a pull request to fix this? The methods should be added to the `Matrix` class here: https://github.com/mljs/matrix/blob/ec07f0f189006f31a78fa459335328b555ac7959/matrix.d.ts#L901-L905
