### ISSUE TITLE
Error build jupyterlab with ml-matrix

### ISSUE THREAD

**Issue by trungleduc** [mljs/matrix#112]
Hello,
I got following error while using ml-matrix with a JupyterLab extension.

`    ERROR in vendors~main.1a6067ba633abf1df8f1.js from Terser
    Unexpected token: punc ()) [./node_modules/ml-matrix/src/util.js:44,0][vendors~main.1a6067ba633abf1df8f1.js:800393,4]`

Do you have any idea where does this error come from?

**Comment by maasencioh** [comment]
Hello @trungleduc, could you share how did you import it? Thanks

**Comment by trungleduc** [comment]
Actually i do not use ml-matrix directly but i use a library depends on ml-matrix.

This is how they import ml-matrix
https://github.com/antvis/G6/blob/275330171c1a7a2ff86b9af994004f943f9a68cb/src/layout/radial/mds.ts
