### ISSUE TITLE
Support Empty Matrices

### ISSUE THREAD

**Issue by holub008** [mljs/matrix#113]
None of the constructors, nor any of the `remove*` methods allow a matrix to become 0x0. e.g.

```js
const m = new Matrix([[0]]);
m.removeRow(0);
// RangeError: A matrix cannot have less than one row

const m = new Matrix(0, 0);
// TypeError: First argument must be a positive number or an array
```

Is there a reason not to support empty matrices?

**Comment by targos** [comment]
Let me ask the opposite: Is there a reason for supporting empty matrices?
The library was created 6 years ago and is used in many projects where we never hit this limitation, that's why I'm asking.

We could look into supporting empty matrices, but would have to check the impact on the API.

**Comment by holub008** [comment]
Sure:

- The `0xn` matrix is mathematically valid, and standard matrix operations are well defined (e.g. multiplication, det when `n=0`, etc.) 
- Generality
    - In variable input settings (e.g. regression), it's common to have 0 rows. Client code could add a condition to check for 0 rows, but it would be more elegant to avoid these cases and use ^ mathematical properties.
    - [Here's the example that I ran into](https://github.com/holub008/shukra/blob/master/src/nma.js#L473). When a user triggers the `generalizedNMA` function, I want to give them back a `NetworkMetaAnalysis` object. This is basically a wrapper class on a few matrices. If I can't supply my wrapper with empty matrices when the caller supplies empty data, I am forced to throw an exception, which is not the API I'd like to provide.
- It's supported in other libraries, e.g. R's matrix: `matrix(nrow=0, ncol=2) %*% matrix(c(1, 2), nrow=2)`. Not that this is a reason on its own, but developers may have expectations from using other libs.

Changing this behavior would probably warrant a major version bump, given that some clients may depend on exceptions for empty matrices. I'm not sure major bumping a 6 year old stable library is feasible. Especially for a relatively trivial change, but I wanted to test the waters e.g. if you already have a major release we could tie it into.

**Comment by targos** [comment]
> Changing this behavior would probably warrant a major version bump, given that some clients may depend on exceptions for empty matrices.

Not sure about that. Usually we don't consider removing a thrown exception to be semver-major.

Would you like to try and open a PR to remove the limitation?

**Comment by holub008** [comment]
Definitely!

**Comment by holub008** [comment]
For operations requiring value initialization, (e.g. row or column sums), what do you think the appropriate return value is when the matrix is 0-dimensional?

I think either returning an array of `0`s, `NaN`s or throwing an exception would be reasonable.

```js
(new Matrix(0,0)).sum('row') // []
(new Matrix(1, 0)).sum('row') // [NaN] or [0]
```

For reference, R uses the [nullary sum](https://en.wikipedia.org/wiki/Empty_sum)
```js
> rowSums(matrix(nrow=2,ncol=0))
[1] 0 0
> rowMeans(matrix(nrow=2,ncol=0))
[1] NaN NaN
```

If we like the nullary sum, it obviously generalizes to subtraction as well as [multiplication/division](https://en.wikipedia.org/wiki/Empty_product).
