### ISSUE TITLE
6.8.1 cannot be installed

### ISSUE THREAD

**Issue by DerYeger** [mljs/matrix#131]
The latest version 6.8.0 cannot be installed.
Instead, the installation either fails (in CI) or prompts version selection (with 6.8.0 being the latest available).
The Renovate bot also can't update to 6.8.1.

See https://github.com/DerYeger/apollo-frontend/runs/4179031612?check_suite_focus=true for logs showing the problem.

**Comment by stropitek** [comment]
Indeed something strange happened. Latest points to 6.8.1 according to https://www.npmjs.com/package/ml-matrix but that's not the version that gets installed when you install latest.

I can also confirm that installing this specific version with npm8 fails.

I'll publish a new version, this is probably a one-off problem with npm

**Comment by stropitek** [comment]
Same problem with 6.8.2, so not a one off problem 😅

**Comment by DerYeger** [comment]
That's weird. My Renovate run seems to be passing https://github.com/DerYeger/apollo-frontend/pull/101.

**Comment by stropitek** [comment]
https://github.com/mljs/matrix/commit/2e1447d75e3c2fe2450f474d15336f8ae2a26d5f changed the release action, so that could be the culprit. I'm not sure where to look at though because the action does not seem to have failed in any way.

**Comment by stropitek** [comment]
Actually, I'm able to install it now. I tried to soon after publication I suppose

**Comment by DerYeger** [comment]
Most likely. Thank you again!
