### ISSUE TITLE
fail to create specify matrix

### ISSUE THREAD

**Issue by dantecsm** [mljs/matrix#135]
```javascriipt
const { Matrix } = require('ml-matrix');

var A = new Matrix([[0, 1, 0], [-1, 0, 1], [0, 0, 1]]);
```

![image](https://user-images.githubusercontent.com/35835538/147430624-bf3d3e1f-9f23-4f20-9c51-ad9cbe904472.png)

**Comment by stropitek** [comment]
I'm not familiar with runkit, but this code runs in node 14 so likely an issue related to runkit

**Comment by targos** [comment]
I'm going to close this as the provided code works in Node.js and we do not use RunKit.
