### ISSUE TITLE
muliply i,k matrix with k,j matrix

### ISSUE THREAD

**Issue by lars1974** [mljs/matrix#138]
Great library. I miss a feature that multiply two matrices like e.g. [[1, 2], [3, 4]*[[1], [2]] = [[3], [7]] by something like:

 static multiply(a: Matrix, b: Matrix): Matrix {
        const c = Matrix.zeros(a.rows, b.columns)
        for (let i = 0; i < a.rows; i++) {
            for (let j = 0; j < b.columns; j++) {
                for (let k = 0; k < a.columns; k++) {
                    c.set(i, j, c.get(i,j) + a.get(i, k) * b.get(k, j))
                }
            }
        }
        return c;
    }

But you already have som multiply functions that do different

**Comment by targos** [comment]
Matrix multiplication is implemented in the `mmul` method.
