### ISSUE TITLE
is it implemented the `linear sum assignment problem' solver?

### ISSUE THREAD

**Issue by jobo322** [mljs/matrix#147]
@targos there is a nice feature that we need to search solvent multiple in nmr spectrum.
[linear sum assignment](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html) from scypy could be helpful to test this if it is not implemented yet.

**Comment by targos** [comment]
I don't know what it is

**Comment by maasencioh** [comment]
This is an optimization problem; therefore, I don't think it should be in this package.
I think you could try to implement it using simplex, as [they describe here](https://en.wikipedia.org/wiki/Assignment_problem#Solution_by_linear_programming).

**Comment by jobo322** [comment]
@maasencioh many thanks I will implement it.
