### ISSUE TITLE
null values are converted to 0 without warning

### ISSUE THREAD

**Issue by chrispahm** [mljs/matrix#148]
When playing with the following dataset (https://archive.ics.uci.edu/ml/datasets/seeds#), I realised that the column means calculated by `ml-matrix` were different (wrong) when compared to R.
It turns out that [`Float64Array.from(arrayData[i])`](https://github.com/mljs/matrix/blob/687de4fd29d55596423a8ef8a654977a50d0509c/src/matrix.js#L1565) silently converts null values to 0 without any warning/error. 
Any idea on how to improve here?

**Comment by stropitek** [comment]
We can't have the same behavior as R since we use typed arrays

My suggestion would be to throw an error if a matrix is initialized with anything which is not a number

**Comment by chrispahm** [comment]
Alright, see #149 for a suggestion
