### ISSUE TITLE
About Private properties # need babel support

### ISSUE THREAD

**Issue by liuzeyang** [mljs/matrix#180]
![image](https://github.com/mljs/matrix/assets/15833097/56b5c8d6-6e93-49bb-9e16-63854a57cd72)

i find error in matrix, need add babel plugin to support that 
 "plugins": [
    "@babel/plugin-proposal-private-methods",
    "@babel/plugin-proposal-private-property-in-object"
  ]

**Comment by tpoisseau** [comment]
Hello,

I'm sorry it breaks on your code.
Our publishing policy is to **not transpile** our code and expect a reasonable modern runtime to run it.

According to ["Can I use"](https://caniuse.com/?search=class%20field) public, private class fields and private methods have been supported for 2 years. So we estimate that it is OK to use it.

Thanks for your feedback and your workaround. I hope it will be useful if someone else has the same error.

Best regards

**Comment by lmran** [comment]
why close this issue?

**Comment by Tryerman** [comment]
I have some kind of this issue, but your resolve doesn`t work for me ...

What i do wrong ?

Failed to compile.

This my issue

```
./node_modules/ml-matrix/src/symmetricMatrix.js 7:2
Module parse failed: Unexpected character '#' (7:2)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export class SymmetricMatrix extends AbstractMatrix {
|   /** @type {Matrix} */
>   #matrix;
|   get size() {
|     return this.#matrix.size;

```

**Comment by Tryerman** [comment]
Not work
I tryed

**Comment by XiayidanAlimu** [comment]
# Question
Attempt to import package `butterfly-dag` by loading on demand, but this introduces an compiling error in my project, this error is related to one of its dependencies: `ml-matrix`

# Environment
1. ml-matrix@6.11.0
2. butterfly-dag@4.3.29
3. vue@2.7.8

# Steps to reproduce

importing butterfly-dag from `fully import` to `load on demande` 

### before ( `fully import` )
```javascript
import { Node, Tips } from 'butterfly-dag'
```
This works all fine, but the bundled package size is too much, I want to reduce the package size for optimization concern.

### after (`load on demande` )
```javascript
import { Node, Tips } from 'butterfly-dag/pack/index.js'
```

# Solutions Tried
I tried to add the following configurations as mentioned above in my project ./vue.config.js :

```javascript
"plugins": [
"@babel/plugin-proposal-private-methods",
"@babel/plugin-proposal-private-property-in-object"
]
```

but I still have this error : 
![image](https://github.com/mljs/matrix/assets/22473904/427a0443-b7e3-4925-bb57-46fb7433dc47)

I see in some issues answer, which suggest changing the version of ml-matrix, but in my context, this is a dependency imported by another dependency, so I may could not specify the version of the package `ml-matrix`
