### ISSUE TITLE
Unexpected character '#' (7:2)

### ISSUE THREAD

**Issue by Victor-Go** [mljs/matrix#185]
I'm using create-react-app to create my app and I don't have babel and webpack in my project.
In my project, I've used antd-charts lib which has used ml-matrix.
When I tried to start my app, I encountered the following issue.

```
./node_modules/ml-matrix/src/symmetricMatrix.js 7:2
Module parse failed: Unexpected character '#' (7:2)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export class SymmetricMatrix extends AbstractMatrix {
|   /** @type {Matrix} */
>   #matrix;
|   get size() {
|     return this.#matrix.size;
```

Are there any workarounds for this issue?

**Comment by targos** [comment]
See https://github.com/mljs/matrix/issues/180
