### ISSUE TITLE
does not support below ES6?

### ISSUE THREAD

**Issue by keonkim** [mljs/matrix#20]
there are codes that are unsupported in previous Node.js (ex, 0.12).
such as class statements. 

Is this intended?

**Comment by targos** [comment]
Yes it is intended for v1.x. 
If you need older Node.js compatibility, you can use version 0.1.0 which doesn't have ES6 code.

**Comment by keonkim** [comment]
but wouldn't it prevent others from using it on browsers?
Or is it not intended for browser usability?

**Comment by targos** [comment]
The only issue is with Firefox (it doesn't support subclassing Array).
I just made an update to support Safari, so this library works on Chrome, Safari and Edge.

**Comment by glebmachine** [comment]
It is not(
It's about 13% of all browsers globally https://caniuse.com/#feat=es6-class

Here need to be done the same as we done with @stropitek here: https://github.com/mljs/array/commit/50f16bf02e0a0cf5f1b9c5288f393128d9a2f6e1

**Comment by glebmachine** [comment]
You have following code in distributes js ![](http://joxi.ru/Dr8O09lU43an9A.jpg)
