### ISSUE TITLE
supported version

### ISSUE THREAD

**Issue by maasencioh** [mljs/matrix#26]
Hello, is the supported node version >=2.0.0?

Because this [test](https://tonicdev.com/56bd9d09452c730d00b8098f/56bd9d09452c730d00b80990) is failing for that version, so maybe it's >2.0.0

**Comment by targos** [comment]
I just tested on v2.0.0 and it works:
```
test % node -v
v2.0.0
test % node   
> var Matrix = require('ml-matrix')
undefined
> var m = new Matrix(2,2)
undefined
> m.fill(2).div(4).to1DArray()
[ 0.5, 0.5, 0.5, 0.5 ]
```

The link you posted was apparently executed on v0.12.10 which is not supported.

**Comment by maasencioh** [comment]
you're right, that apparently npm isn't able to know the supported version based in the dependencies
