### ISSUE TITLE
The documentation should be updated

### ISSUE THREAD

**Issue by maasencioh** [mljs/matrix#4]

**Comment by morenoh149** [comment]
A api should be added (list of operations exposed by this library). Or a page in the wiki you link to from the readme. Let me know if you need help.

**Comment by targos** [comment]
I made an effort to document the methods in the code using jsdoc. We just need to generate the API doc from it

**Comment by targos** [comment]
documentation has been generated in markdown using [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown): https://github.com/mljs/matrix/blob/master/Documentation.md

I will check another time if it's possible to document the dynamically added methods and the decomposition algorithms
