### ISSUE TITLE
TypedArrays and Other Functions

### ISSUE THREAD

**Issue by zafarali** [mljs/matrix#45]
Hi!

Thanks for this great library, something that JavaScript desperately needs. I am looking to contribute to it in my free time.

Here are some improvements and new functions I could think of:
1. `Matrix.det()`. Even though ML operations (in my limited experience) do not seem to need this, it would be good to have it for completeness and  generalization
2. [Use of TypedArrays to store data](https://www.html5rocks.com/en/tutorials/webgl/typed_arrays/). For example, one can create a subclass that was TypedMatrix which would implement the main `get`, `set`, etc functions.

Do you think it would be a good addition and are there any open issues that could use some coding?

Zaf

**Comment by targos** [comment]
Hello!

Thank you for your interest. It's great to see that other people are interested in our work!
You are welcome to make contributions to this project and any other that you like in the mljs organization :)

About the two improvements:
1. I think it makes perfect sense to add a `det()` method. The more general the library is, the more interesting it will be for the users. About the implementation, I guess there can be fast paths for the 2x2 and 3x3 cases.
2. Absolutely. Support for 1D arrays has always been in my todo list and I'd be really happy to review a PR adding it! I don't think it has to be specific to TypedArrays (plain `Array` objects should work too), unless there is a clear win in speed.

Don't hesitate to ask if you need help to understand the code base.

**Comment by zafarali** [comment]
I found this https://github.com/scijs/ndarray that seems to provide a speed improvement over using arrays of arrays using strides and a single `Float64Array`. Perhaps we can use that or incorporate some ideas from there?

**Comment by targos** [comment]
It seems very interesting indeed!
