### ISSUE TITLE
Norm

### ISSUE THREAD

**Issue by jajoe** [mljs/matrix#53]
I don't find any function which compute the norm of a matrix (e.g Frobenius norm). Does it exists or not already ?

**Comment by targos** [comment]
It doesn't exist. You are welcome to implement it :)

**Comment by jajoe** [comment]
```js
function norm2(A){
  var result = 0;
  for(var i = 0; i < A.rows; i++){
    for(var j = 0; j < A.columns; j++){
      result = result + Math.abs(A.get(i,j))**2;
    }
  }
  return Math.sqrt(result);
}
```
Après je ferai sûrement une fonction norm qui prend en options le type de norme qu'elle veut. J'ajouterai ça quand j'aurai fini le NMF

**Comment by targos** [comment]
Implemented in https://github.com/mljs/matrix/commit/221391ae8c40250209ed2c9641e258de1d922a80
