### ISSUE TITLE
Should abandon this project?

### ISSUE THREAD

**Issue by andcastillo** [mljs/matrix#6]
mathjs + numeric.js are great tools that can work together and cover all the functionalities of this library with a lot of support.

**Comment by maasencioh** [comment]
may be, but those are much heavier than this library

**Comment by targos** [comment]
Thanks for your concern but I do not intend to abandon this project in a near future.

mathjs is great but doesn't provide the same functionalities AFAIK.
numeric.js does similar things but isn't being maintained anymore and uses old JavaScript concepts.

I created ml-matrix because I wanted a library with an object-oriented, chainable, approach and I couldn't find any on npm. I am currently working on a refactoring that will enhance the overall performance and make the code more modern by using ES6 features ([wip here](https://github.com/mljs/matrix/tree/es6)).

One could argue that the library shouldn't be used because it's slow, so I compared it with numeric for a few use cases. Here are the benchmarking results:

### Chaining operations

Code (here you see the advantage in readability of the chainable API):
```js
// ml-matrix
matrix.subS(5).mulS(Math.PI).abs();

// numeric
numeric.abs(numeric.muleq(numeric.subeq(matrix, 5), Math.PI));
```

Result:
```
Chain operations benchmark for 5x5 matrix
ES5 x 10,106,421 ops/sec ±0.18% (102 runs sampled)
ES6 x 10,133,354 ops/sec ±0.36% (98 runs sampled)
numeric x 2,593,745 ops/sec ±0.32% (102 runs sampled)

Chain operations benchmark for 100x100 matrix
ES5 x 41,065 ops/sec ±0.32% (100 runs sampled)
ES6 x 41,325 ops/sec ±0.10% (95 runs sampled)
numeric x 22,992 ops/sec ±0.46% (101 runs sampled)

Chain operations benchmark for 90x60 matrix
ES5 x 68,114 ops/sec ±0.48% (100 runs sampled)
ES6 x 69,756 ops/sec ±0.33% (93 runs sampled)
numeric x 39,280 ops/sec ±0.29% (99 runs sampled)
```

### Eigenvalue decomposition
```
EVD benchmark for 5x5 matrix
ES5 x 110,002 ops/sec ±0.29% (101 runs sampled)
ES6 x 146,206 ops/sec ±0.20% (101 runs sampled)
numeric x 5,880 ops/sec ±8.05% (96 runs sampled)

EVD benchmark for 100x100 matrix
ES5 x 4.04 ops/sec ±0.96% (11 runs sampled)
ES6 x 60.04 ops/sec ±0.61% (64 runs sampled)
numeric x 1.12 ops/sec ±1.21% (7 runs sampled)
```

### Singular value decomposition
```
SVD benchmark for 5x5 matrix
ES5 x 93,082 ops/sec ±0.33% (101 runs sampled)
ES6 x 144,155 ops/sec ±0.22% (98 runs sampled)
numeric x 240,237 ops/sec ±0.59% (97 runs sampled)

SVD benchmark for 100x100 matrix
ES5 x 56.92 ops/sec ±39.37% (70 runs sampled)
ES6 x 61.78 ops/sec ±6.71% (69 runs sampled)
numeric x 82.31 ops/sec ±9.39% (76 runs sampled)

SVD benchmark for 90x60 matrix
ES5 x 180 ops/sec ±44.09% (90 runs sampled)
ES6 x 184 ops/sec ±12.86% (94 runs sampled)
numeric x 243 ops/sec ±24.21% (92 runs sampled)
```

**Comment by targos** [comment]
to be fair I added mathjs to the chaining benchmark

**Comment by andcastillo** [comment]
To be fair you need something else. I can do something unfair to benefit mathjs too: 

ES5 x 0.91 ops/sec ±7.35% (7 runs sampled)
mathjs x 551 ops/sec ±1.18% (89 runs sampled)
Fastest is mathjs

suite.add('ES5', function() {
        var m2 = new Matrix.eye(5000);
        var m3 = m2.clone();
        m2.add(m3).add(m3);
    })
    .add('mathjs', function() {
        var m1 = math.eye(5000,5000,"sparse");
        m1._datatype= 'number';
        m1 = math.chain(m1).add(m1).add(m1).done();
        
    })
    .on('cycle', function(event) {
        console.log(String(event.target));
    })
    .on('complete', function() {
        console.log('Fastest is ' + this.filter('fastest').pluck('name'));
    })
    .run({ 'async': true });

**Comment by andcastillo** [comment]
But I agree. It is really slow for dense matrixes. The project of sparce matrices is young and they have issues because its performance for dense.

**Comment by targos** [comment]
Why are you bringing sparse matrices here? This library does not pretend to support / be optimized for them.
The original development was made to have the methods needed by the PCA, which is applied on fully dense matrices

**Comment by andcastillo** [comment]
Come on. That was just an example of how a bad benchmark can shows whatever you want.  I did this one. In this case the results shows 10X instead of 100X. That is more fair: 

ES5 x 3.35 ops/sec ±1.34% (13 runs sampled)
mathjs x 0.39 ops/sec ±22.50% (6 runs sampled)
Fastest is ES5

var m1 = math.eye(5000,5000,"dense");
var m2 = new Matrix.eye(5000);
var m3 = m2.clone();
suite.add('ES5', function() {
        m2.add(m3).add(m3);
    }).add('mathjs', function() {
        m1 = math.chain(m1).add(m1).add(m1).done();
    }).on('cycle', function(event) {
        console.log(String(event.target));
    }).on('complete', function() {
        console.log('Fastest is ' + this.filter('fastest').pluck('name'));
    }).run({ 'async': true });
