### ISSUE TITLE
Trouble Integrating with webpack

### ISSUE THREAD

**Issue by mcnuttandrew** [mljs/matrix#69]
Cool library! It's so fast!

I used the eigenvalue decomposition function from ml-matrix as part of a library that I developed in node, and it worked really well there. I'm trying to bring it over to the browser and I've been having trouble importing it in a webpack build. It's totally the case that most webpack bugs tend to be due to the configurer, but I saw you recently were flipping some stuff around on exports and wanted to double checked.

Specifically my bug is that webpack throws somewhat opaquely on in base.js like so

```js
base.js:4 Uncaught TypeError: __webpack_require__.i(...) is not a function
    at Object.<anonymous> (base.js:4)
    at __webpack_require__ (bootstrap 240ca1a7412a4a4ff7b3:659)
    at fn (bootstrap 240ca1a7412a4a4ff7b3:83)
    at Object.<anonymous> (sub.js:28)
    at __webpack_require__ (bootstrap 240ca1a7412a4a4ff7b3:659)
    at fn (bootstrap 240ca1a7412a4a4ff7b3:83)
    at Object.<anonymous> (number.js:3)
    at __webpack_require__ (bootstrap 240ca1a7412a4a4ff7b3:659)
    at fn (bootstrap 240ca1a7412a4a4ff7b3:83)
    at Object.<anonymous> (ascending.js:3)
(anonymous) @ base.js:4
__webpack_require__ @ bootstrap 240ca1a7412a4a4ff7b3:659
fn @ bootstrap 240ca1a7412a4a4ff7b3:83
(anonymous) @ sub.js:28
__webpack_require__ @ bootstrap 240ca1a7412a4a4ff7b3:659
fn @ bootstrap 240ca1a7412a4a4ff7b3:83
(anonymous) @ number.js:3
__webpack_require__ @ bootstrap 240ca1a7412a4a4ff7b3:659
fn @ bootstrap 240ca1a7412a4a4ff7b3:83
(anonymous) @ ascending.js:3
__webpack_require__ @ bootstrap 240ca1a7412a4a4ff7b3:659
fn @ bootstrap 240ca1a7412a4a4ff7b3:83
(anonymous) @ event.js:73
__webpack_require__ @ bootstrap 240ca1a7412a4a4ff7b3:659
fn @ bootstrap 240ca1a7412a4a4ff7b3:83
(anonymous) @ k-shape.js:4
__webpack_require__ @ bootstrap 240ca1a7412a4a4ff7b3:659
fn @ bootstrap 240ca1a7412a4a4ff7b3:83
(anonymous) @ app.js:4
__webpack_require__ @ bootstrap 240ca1a7412a4a4ff7b3:659
fn @ bootstrap 240ca1a7412a4a4ff7b3:83
(anonymous) @ log-apply-result.js:30
__webpack_require__ @ bootstrap 240ca1a7412a4a4ff7b3:659
module.exports @ bootstrap 240ca1a7412a4a4ff7b3:708
(anonymous) @ bootstrap 240ca1a7412a4a4ff7b3:708
client?e36c:38 
```

Feel free to close if you think the error is on my end

**Comment by targos** [comment]
Hi, thank you for the kind words! I already bundled the library successfully with webpack but as you say, it could be due to a recent change. What browser do you use?

**Comment by mcnuttandrew** [comment]
I'm on latest chrome. It doesn't appear to be due to browsers though (tested on safari too). The problem is really weird. I also tried running my library through browserify as a build step, and then required that in a webpack app, which gives a new error, in which it appears that the classes are stripped out? Eg running this code from the tests:

```js
var testMatMat = new Matrix([[1, 0], [1, 3]]);
var evdddd = new EVD(testMatMat);
```

Yields an error like:

```sh
dist.min.js:4525 Uncaught TypeError: matrix.isSquare is not a function
    at new EigenvalueDecomposition$$1 (dist.min.js:4525)
    at Object.9.d3-array (dist.min.js:9891)
    at o (dist.min.js:1)
    at r (dist.min.js:1)
    at dist.min.js:1
    at dist.min.js:1
    at Object.<anonymous> (dist.min.js:1)
    at Object.defineProperty.value (bundle.js:40559)
    at __webpack_require__ (bootstrap ff84e41df1ddd1267419:659)
    at fn (bootstrap ff84e41df1ddd1267419:83)
```

If you could point me at a app that uses webpack for compilation, so I could try to understand how to work things by example it would be much appreciated

**Comment by JuliusSkrisa** [comment]
Hi guys, I have exactly same issue on the same line in base.js:4.

`export default class BaseView extends AbstractMatrix() {`

AbstractMatrix is not a function after webpack processes  the code in my case.

**Comment by xhaldos** [comment]
I have the same issue with react-native.cli: 2.0.1 / react-native: 0.56.0 

`export default class BaseView extends AbstractMatrix() {
`

**Comment by ksesong** [comment]
Using `react-native` as well, same issue, I cannot initialize any matrix. Any workaround?

**Comment by 0tho** [comment]
The problem seems to be that that ml-matrix extends native Array class and somehow webpack messes it up while import ml-matrix. If you try to look it up on console a instance of Matrix it looks like just a "flat" Array without any extra methods.

[This](https://stackoverflow.com/questions/35128241/extreme-es6-array-extension-weirdness-it-reverts-to-regular-array-with-webpack) is the closest report I could find about array extension problems.

**Comment by targos** [comment]
I'm probably going to stop extending the native Array class in the next major release, and instead keep the array in an internal slot, like it's done in [WrapperMatrix2D](https://github.com/mljs/matrix/blob/master/src/wrap/WrapperMatrix2D.js)

**Comment by targos** [comment]
You can try the next major version with `npm install ml-matrix@next`. I made sure it works with `create-react-app` and even on IE11 (after including `@babel/polyfill`)

**Comment by targos** [comment]
Version 6.0.0 is now released and should fix this issue.
