### ISSUE TITLE
Add methods isEchelonForm and isReducedEchelonForm

### ISSUE THREAD

**Issue by lpatiny** [mljs/matrix#75]
Implement a fast algorithm that checks if the matrix is echelonForm or reducedEchelonForm

https://en.wikipedia.org/wiki/Row_echelon_form

Add methods:
* isEchelonForm( options = {kind='row', threshold=Number.EPSILON}) (kind is row or column, threshold is the Math.abs under (or equal) which the value is considered as 0), return true / false 
* isReducedEchelonForm( options = {kind='row'', threshold=Number.EPSILON}) (kind is row or column), return true / false 

Add corresponding testcases

**Comment by Goneiross** [comment]
solved

**Comment by targos** [comment]
Fixed in https://github.com/mljs/matrix/pull/84
