### ISSUE TITLE
SVD sign error

### ISSUE THREAD

**Issue by MatteoBassan** [mljs/matrix#83]
I'm trying to calculate SVD values for known matrices, while comparing results with MATLAB and php output for the same matrix. Everything is the same except from sign.

Here's an example using this code:

` var uval = new SingularValueDecomposition(mymatrix,{autoTranspose:true})
       var U = new Matrix(uval.U);
        console.log(U) `

and this matrix:
`[[2,0,2],[0,1,7],[0,0,0]]`

The expected result is this:

`[0.2898,  -0.9571,   0.0000],
   [0.9571,   0.2898,   0.0000],
   [0.0000,   0.0000,   1.0000]`

but the function actually returns this:

`[ 0.2898, 0.9571, 0 ],
 [ 0.9571, -0.2898, 0 ],
 [ 0, 0, 1 ]`
What's wrong with these signs? Am I missing something?

**Comment by teemupiiroinenwirepas** [comment]
The result seems to be correct, as when you recreate the matrix from the SVD parts, you get (almost) the original matrix.

```
let uval = new SingularValueDecomposition([[2,0,2],[0,1,7],[0,0,0]]);

let U = new Matrix(uval.U);
let V = new Matrix(uval.V);

let S = Matrix.zeros(3, 3);
S.set(0, 0, uval.s[0]);
S.set(1, 1, uval.s[1]);
S.set(2, 2, uval.s[2]);

let M = U.mmul(S).mmul(V.transpose());
```
M = [ 2, 5.551115123125783e-17, 1.9999999999999996 ], [ 1.1102230246251565e-16, 1.0000000000000002, 7.000000000000001 ], [ 0, 0, 0 ]

**Comment by bryangingechen** [comment]
The columns of the U and V matrices are only unique up to multiplication by a sign: https://en.wikipedia.org/wiki/Singular_value_decomposition#Singular_values,_singular_vectors,_and_their_relation_to_the_SVD

**Comment by targos** [comment]
Thanks for the explanations. I'm closing this as answered.
