### ISSUE TITLE
eye and diag

### ISSUE THREAD

**Issue by andcastillo** [mljs/matrix#9]
I think eye and diag functions should be compatible with the Matlab versions, which are not necessary for square matrices.  
B = eye(3,4)
B =
     1     0     0     0
     0     1     0     0
     0     0     1     0
diag(B)
ans =
     1
     1
     1
C =  diag(diag(B))
C =
     1     0     0
     0     1     0
     0     0     1

**Comment by targos** [comment]
ok why not, I'll do it

**Comment by targos** [comment]
done in the es6 branch:

```
> B = Matrix.eye(3,4)
Matrix [
  [ 1, 0, 0, 0 ],
  [ 0, 1, 0, 0 ],
  [ 0, 0, 1, 0 ],
  rows: 3,
  columns: 4 ]
> B.diag()
[ 1, 1, 1 ]
> C = Matrix.diag(B.diag())
Matrix [ [ 1, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 1 ], rows: 3, columns: 3 ]
```

**Comment by targos** [comment]
fixed on master
