### ISSUE TITLE
get vector from a given column or row

### ISSUE THREAD

**Issue by thegodone** [mljs/matrix#98]
How to get the vector in a matrix object ?

**Comment by lpatiny** [comment]
Do you mean extract a row or column of the matrix and get it as an array ?

* https://mljs.github.io/matrix/classes/matrix.html#getcolumn
* https://mljs.github.io/matrix/classes/matrix.html#getRow

```js
const { Matrix } = require('ml-matrix');

let matrix = new Matrix([
  [1, 2],
  [3, 4]
]);
let secondRow = matrix.getRow(1);
console.log(secondRow);
```
